### ISSUE TITLE
Skipping checks for Yarn / npm workspaces

### ISSUE THREAD

**Issue by kachkaev** [raineorshine/npm-check-updates#1217]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates` (16.3.18)
- [x] I am using `node >= 14.14`

---

👋 @raineorshine! When I run `ncu` in a monorepo with `--workspaces` (or `--deep`) option, I see warnings like this:

```
404 Not Found - GET https://registry.npmjs.org/some-local-package. Either your internet connection is down or unstable and all 3 retry attempts failed, or the registry is not accessible, or the package does not exist. 
```

When `ncu` scans workspace `package.json` files, it does not distinguish between the references to third-party npm packages and local workspaces, which are sourced from the sibling folders. It’d be nice if `ncu` skipped workspace references by default.

## Steps to Reproduce

You can try running `ncu --workspaces` in one of monorepo examples: https://github.com/vercel/turbo/tree/main/examples. Alternatively, you can clone https://github.com/blockprotocol/blockprotocol and run `ncu` from the root.

You can also use this MWE:

```sh
mkdir /tmp/ncu-1217
cd /tmp/ncu-1217

cat << EOF > package.json
{
  "private": true,
  "workspaces": [
    "packages/*"
  ]
}
EOF


mkdir -p packages/some-local-package packages/some-local-app

cat << EOF > packages/some-local-package/package.json
{
  "name": "some-local-package",
  "version": "0.4.2",
  "dependencies": {
    "eslint": "1.0.0"
  }
}
EOF

cat << EOF > packages/some-local-app/package.json
{
  "name": "some-local-app",
  "dependencies": {
    "some-local-package": "0.4.2",
    "eslint": "1.0.0"
  }
}
EOF

npx npm-check-updates@16.3.18 --workspaces
```

## Current Behavior

References to other workspaces are checked.

In the MWE:

```
Checking /private/tmp/example-repo/packages/some-local-app/package.json
[==========----------] 1/2 50%
 eslint  1.0.0  →  8.27.0

 some-local-package  404 Not Found - GET https://registry.npmjs.org/some-local-package. Either your internet connection is down or unstable and all 3 retry attempts failed, or the registry is not accessible, or the package does not exist. 

Run npx npm-check-updates --workspaces -u to upgrade packages/some-local-app/package.json
Checking /private/tmp/example-repo/packages/some-local-package/package.json
[====================] 1/1 100%

 eslint  1.0.0  →  8.27.0
```

## Expected Behavior

References to other workspaces are ignored.

In the MWE:

```
Checking /private/tmp/example-repo/packages/some-local-app/package.json
[==========----------] 1/1 100%
 eslint  1.0.0  →  8.27.0

Run npx npm-check-updates --workspaces -u to upgrade packages/some-local-app/package.json
Checking /private/tmp/example-repo/packages/some-local-package/package.json
[====================] 1/1 100%

 eslint  1.0.0  →  8.27.0
```

## Additional thoughts

I think it’s fine to keep the current behavior when running `ncu --deep` because in this case we are not necessarily running `ncu` in a monorepo. I can also imagine some option that distinguishes between links to workspaces with `"prviate": true` and those that actually get published, but I struggle to come up with an example where different behaviour would be needed. Just passing the full list of workspaces to the ignore list should be a good start IMHO.

**Comment by raineorshine** [comment]
In addition to the general description in current and expected behavior, can you provide a concrete description of the particular current and expected behavior of one your test cases? Just to make sure I'm on the same page. Thanks!

**Comment by raineorshine** [comment]
Fixed and published in `v16.3.21`

**Comment by kachkaev** [comment]
Thanks @raineorshine! https://github.com/raineorshine/npm-check-updates/commit/f13fd29f37fc3267737783f94be94b77319d4065 makes sense and it should cover many cases. In the two monorepo I work in package names do not strictly match folder names so I still get warnings. Basically this line does not work for me:

```js
workspacePackages = workspacePackageFiles.map(file => file.split('/').slice(-2)[0])
```

What `ncu` can do to address this is reading package files and extracting names from them. Alternatively we can get package names from `yarn workspaces info` if available.

Package examples:
- [packages/@local/eslint-config](https://github.com/blockprotocol/blockprotocol/blob/d96b316ce8385b3eae0e5ff810557d0f8e1772da/packages/%40local/eslint-config/package.json#L2) → `@local/eslint-config`

- [packages/hash/api](https://github.com/hashintel/hash/blob/6ade0244dcc7caae9748a1a8c177da0769b32260/packages/hash/api/package.json#L2) → `@hashintel/hash-api`

**Comment by raineorshine** [comment]
Ah, I see. I hadn't thought of that.

Should be fixed up and published in `v16.3.22`.

**Comment by kachkaev** [comment]
`v16.3.22` works like a charm ✨ Big thanks for fixing this bug so quickly and happy Friday 🙌 🎉
